/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ni.edu.uni.programacion.views.panels;

import javax.swing.JButton;
import javax.swing.JTextField;

/**
 *
 * @author GABO
 */
public class PnlConversor extends javax.swing.JPanel {

    /**
     * Creates new form PnlConversor
     */
    public PnlConversor() {
        initComponents();
    }

    public JButton getBtnConv1() {
        return BtnConv1;
    }

    public void setBtnConv1(JButton BtnConv1) {
        this.BtnConv1 = BtnConv1;
    }

    public JButton getBtnConv2() {
        return BtnConv2;
    }

    public void setBtnConv2(JButton BtnConv2) {
        this.BtnConv2 = BtnConv2;
    }

    public JTextField getTxtConv1() {
        return TxtConv1;
    }

    public void setTxtConv1(JTextField TxtConv1) {
        this.TxtConv1 = TxtConv1;
    }

    public JTextField getTxtConv2() {
        return TxtConv2;
    }

    public void setTxtConv2(JTextField TxtConv2) {
        this.TxtConv2 = TxtConv2;
    }

    public JButton getBtnConv3() {
        return BtnConv3;
    }

    public void setBtnConv3(JButton BtnConv3) {
        this.BtnConv3 = BtnConv3;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        BtnConv1 = new javax.swing.JButton();
        BtnConv2 = new javax.swing.JButton();
        BtnConv3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TxtConv1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TxtConv2 = new javax.swing.JTextField();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        BtnConv1.setText("Cordoba a Dolar");
        BtnConv1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnConv1ActionPerformed(evt);
            }
        });
        jPanel1.add(BtnConv1);

        BtnConv2.setText("Dolar a Cordoba");
        BtnConv2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnConv2ActionPerformed(evt);
            }
        });
        jPanel1.add(BtnConv2);

        BtnConv3.setText("Limpiar");
        jPanel1.add(BtnConv3);

        add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Moneda");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel2.add(jLabel1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel2.add(TxtConv1, gridBagConstraints);

        jLabel2.setText("Conversion");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel2.add(jLabel2, gridBagConstraints);

        TxtConv2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtConv2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        jPanel2.add(TxtConv2, gridBagConstraints);

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void TxtConv2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtConv2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtConv2ActionPerformed

    private void BtnConv1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnConv1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnConv1ActionPerformed

    private void BtnConv2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnConv2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnConv2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnConv1;
    private javax.swing.JButton BtnConv2;
    private javax.swing.JButton BtnConv3;
    private javax.swing.JTextField TxtConv1;
    private javax.swing.JTextField TxtConv2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
